import { City } from "./countr";

export const cities: City[] = [
    { name: "Delhi", state: "Delhi" },
    { name: "Mumbai", state: "Maharashtra" },
    { name: "Kolkata", state: "West Bengal" },
    { name: "Chennai", state: "Tamil Nadu" },
    { name: "Bengaluru", state: "Karnataka" },
    { name: "Hyderabad", state: "Telangana" },
    { name: "Ahmedabad", state: "Gujarat" },
    { name: "Pune", state: "Maharashtra" },
    { name: "Surat", state: "Gujarat" },
    { name: "Jaipur", state: "Rajasthan" },
    { name: "Lucknow", state: "Uttar Pradesh" },
    { name: "Kanpur", state: "Uttar Pradesh" },
    { name: "Nagpur", state: "Maharashtra" },
    { name: "Patna", state: "Bihar" },
    { name: "Indore", state: "Madhya Pradesh" },
    { name: "Bhopal", state: "Madhya Pradesh" },
    { name: "Vadodara", state: "Gujarat" },
    { name: "Visakhapatnam", state: "Andhra Pradesh" },
    { name: "Ranchi", state: "Jharkhand" },
    { name: "Thiruvananthapuram", state: "Kerala" },
    { name: "Chandigarh", state: "Chandigarh" },
    { name: "Guwahati", state: "Assam" },
    { name: "Shimla", state: "Himachal Pradesh" },
    { name: "Dehradun", state: "Uttarakhand" },
    { name: "Agra", state: "Uttar Pradesh" },
    { name: "Varanasi", state: "Uttar Pradesh" },
    { name: "Amritsar", state: "Punjab" },
    { name: "Raipur", state: "Chhattisgarh" },
    { name: "Coimbatore", state: "Tamil Nadu" },
    { name: "Mysuru", state: "Karnataka" }
  ];
  